# 1. Create a 3x3x3 array with random values 

In [14]:
import numpy as np
np.random.random((3,3,3))

array([[[0.70378206, 0.82820012, 0.22367263],
        [0.73281913, 0.86174939, 0.63843036],
        [0.4640284 , 0.21304301, 0.0333478 ]],

       [[0.48099364, 0.2325272 , 0.78338729],
        [0.66980517, 0.81452793, 0.0972001 ],
        [0.87363279, 0.81318918, 0.91328589]],

       [[0.19283436, 0.91804776, 0.95708838],
        [0.87601561, 0.51519706, 0.25824446],
        [0.79284717, 0.64269123, 0.76610731]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [15]:
import numpy as np
x = np.ones((3,3))

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [20]:
x = np.random.random((5,5))
print("The Random Array is : ")
print(x)
xmax , xmin = x.max(), x.min()
x = (x-xmin)/(xmax-xmin)
print("Normalized array is : ")
print(x)

The Random Array is : 
[[0.7411477  0.96322099 0.46313965 0.76266426 0.12083481]
 [0.93353141 0.17036807 0.9607172  0.11660022 0.77442352]
 [0.70129261 0.4526907  0.58403348 0.83803139 0.228193  ]
 [0.51116121 0.36025511 0.52886216 0.49976028 0.99806608]
 [0.49422026 0.9480937  0.68819814 0.85117079 0.38752827]]
Normalized array is : 
[[0.7085328  0.96046915 0.39313994 0.73294278 0.00480403]
 [0.92678709 0.06099823 0.95762866 0.         0.74628335]
 [0.66331824 0.38128587 0.53029082 0.81844482 0.1265991 ]
 [0.44761914 0.27642011 0.46770041 0.43468508 1.        ]
 [0.42840008 0.94330763 0.64846291 0.83335113 0.30736079]]


# 5.  How to find common values between two arrays?

In [23]:
a = np.array([1,2,3,4,5,10])
print("First Array : " , a)
b = np.array([5,6,7,8,9,10])
print("Second Array : " , b)
print("The Common Values between two arrays are :" ,np.intersect1d(a , b))

First Array :  [ 1  2  3  4  5 10]
Second Array :  [ 5  6  7  8  9 10]
The Common Values between two arrays are : [ 5 10]


# 6.How to get the dates of yesterday, today and tomorrow?

In [26]:
Yesterday = np.datetime64('Today' , 'D') - np.timedelta64(1 ,'D')
print("Yesterday : " , Yesterday)
Today = np.datetime64('Today', 'D')
print("Today : ", Today)
Tomarrow = np.datetime64('Today','D') + np.timedelta64(1,'D')
print("Tomarrow : ", Tomarrow)

Yesterday :  2020-07-25
Today :  2020-07-26
Tomarrow :  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [4]:
A = np.array([1,2,3])
B = np.array([4,5,6])
if A.all == B.all:
    print("Both array's are equal")
else:
    print("They are not equal")

They are not equal


In [28]:
print("Two random arrays are equal or not!")
array_equal = np.allclose(A,B)
print(array_equal)

Two random arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [30]:
z = np.random.random(10)
print("Original array:")
print(z)
z[z.argmax()] = 0
print("Maximum value replaced by 0:")
print(z)

Original array:
[0.30911104 0.35962404 0.3913311  0.14943245 0.29554426 0.43522856
 0.43079969 0.04251557 0.47023759 0.04893768]
Maximum value replaced by 0:
[0.30911104 0.35962404 0.3913311  0.14943245 0.29554426 0.43522856
 0.43079969 0.04251557 0.         0.04893768]


# 9. How to print all the values of an array?

In [32]:
a = np.array([1,2,3,4,5,10])
for i in range(len(a)):
    print(a[i])

1
2
3
4
5
10


# 10.Subtract the mean of each row of a matrix

In [35]:
print("Original matrix:")
M = np.array([[10,20,30],[34,56,76]])
print(M)
print("\nSubtract the mean of each row of the said matrix:")
N = M - M.mean(axis=1, keepdims=True)
print(N)

Original matrix:
[[10 20 30]
 [34 56 76]]

Subtract the mean of each row of the said matrix:
[[-10.           0.          10.        ]
 [-21.33333333   0.66666667  20.66666667]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [36]:
z=np.ones(10)
a=np.random.randint(0,len(z),20)
z+=np.bincount(a,minlength=len(z))
print(z)

[4. 3. 4. 3. 4. 2. 3. 3. 1. 3.]


# 12.How to get the diagonal of a dot product?

In [38]:
x = np.array([[1,2,3],[10,20,30],[100,200,300]])
y = np.diag(x.dot(x.T))
print(y)

[    14   1400 140000]


# 13.How to find the most frequent value in an array?

In [44]:
x = np.array([1,23,4,5,6,97,2,19,21,5,2,4,3,4,5,2,4,2,5,3,3,3,3])
print("The Original Array is :\n" , x)
print("The most frequent value is :\n", np.bincount(x).argmax())

The Original Array is :
 [ 1 23  4  5  6 97  2 19 21  5  2  4  3  4  5  2  4  2  5  3  3  3  3]
The most frequent value is :
 3


# 14.How to get the n largest values of an array

In [45]:
x=np.arange(45)
print(x)
np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
[44]


In [46]:
np.max(x)

44

# 15.How to create a record array from a regular array?

In [50]:
a1=np.array([9,8,7,5])
a2=np.array(['Blue','Green','yellow','red'])
a3=np.array([15.78,21,29,45])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])
print(result[3])

(9, 'Blue', 15.78)
(8, 'Green', 21.)
(7, 'yellow', 29.)
(5, 'red', 45.)
